### PR TITLE
Example software codes with explanations

### PR DESCRIPTION
**Pull request by caddison2016**

### CODE REVIEW

**Comment by caddison2016** [comment]
Some sample codes with explanations using wmle (resnet50) and introductory CUDA examples.
Cliff

**Comment by alisonrclarke** [comment]
The CI build failure is down to #25 so we should ignore that for now. I'll reopen the PR to help see what changes have been made.

**Review by alisonrclarke — APPROVED** [review]
Looks good to me from a sphinx point of view but does it need a tech review from someone as well?

**Comment by caddison2016** [comment]
I agree, some comments from others about the technical content are appreciated, but it looks good and (biased view of course) provides some useful information.

Thanks very much,

Cliff

 --

Cliff Addison
Manager
Advanced Research Computing
Computing Services Department
Brownlow Hill Building
University of Liverpool
Liverpool L69 3GG
UK

Phone: +44 151 794 3753
FAX:   +44 151 794 4442

**Comment by caddison2016** [comment]
Looks great. Let's hope we get some technical feedback.
Cliff

**Comment by alisonrclarke** [comment]
@jhodrien Please could you review these changes from a technical point of view? You can download a built copy of the docs from https://github.com/N8-CIR-Bede/documentation/suites/2509933498/artifacts/54280074

**Review by jhodrien — COMMENTED** [review]
Looks generally useful to me, but a couple of comments on the commit.  I'm interested to compare your benchmark results with another system, as I quick skim gives me different figures to you (I'm getting faster than expected results), so I want to drill down and try to find out why.

**Comment by caddison2016** [comment]
The questions about the commit are largely down to my inexperience with both the git process and best practice with documentation via read-the-docs. Linking the in-line code to the actual file is something I should have done – eliminates an update issue. Probably no reason to include the text file bede-README-sbatch.txt. I was thinking about providing a text file that could be downloaded and just kept that file  in place as I moved from providing files on Bede to providing “proper” documentation.

Interesting about the results. We may need to capture more system information in the results when people attempt to reproduce them.

Thanks very much,

Cliff

 --

Cliff Addison
Manager
Advanced Research Computing
Computing Services Department
Brownlow Hill Building
University of Liverpool
Liverpool L69 3GG
UK

Phone: +44 151 794 3753
FAX:   +44 151 794 4442

**Comment by caddison2016** [comment]
I've been trying to follow-up on John's suggestion about linking sbatch_resnet50base.sh from bede-README-sbatch.rst. The issue of a suitable anchor point arises immediately. Locally `sbatch_resnet50base.sh <../../../../software/resnet50/sbatch_resnet50base.sh>`_ works but I really prefer absolute paths or short relative ones. Also do we want an area on bede itself where sample scripts are located (pretty certain we have an area, but could not find it just know) and refer people to that area on bede? 
Cliff

**Comment by alisonrclarke** [comment]
> I've been trying to follow-up on John's suggestion about linking sbatch_resnet50base.sh from bede-README-sbatch.rst. The issue of a suitable anchor point arises immediately. Locally `sbatch_resnet50base.sh <../../../../software/resnet50/sbatch_resnet50base.sh>`_ works but I really prefer absolute paths or short relative ones. Also do we want an area on bede itself where sample scripts are located (pretty certain we have an area, but could not find it just know) and refer people to that area on bede?
> Cliff

I think we'll need to include the file separately - I'll take a look.

**Comment by alisonrclarke** [comment]
One other question: can we shorten the heading "Using Tensorflow, wmlce and ddlrun to do the resnet50 benchmark on multiple nodes [Possibly out of date]"? It's taking up a lot of space on the menu :) 

(I'm going to tidy up the menu for #5 so it's not crucial but would make it look a bit better for now.)

**Comment by caddison2016** [comment]
Certainly, the title in bede-README-sbatch.rst is  Watson Machine Learning Community Edition resnet50 benchmark so the heading could be WMLCE resnet50 benchmark. (Just spotted another typo – I had Environment rather than Edition in bede-README-sbatch.rst – will push out correction when possible).

This probably would work as a sub-heading to the topic that Mark created: PyTorch and TensorFlow: IBM PowerAI and Watson Machine Learning Community Edition (wmlce) [Possibly Out of Date]

Cliff


 --

Cliff Addison
Manager
Advanced Research Computing
Computing Services Department
Brownlow Hill Building
University of Liverpool
Liverpool L69 3GG
UK

Phone: +44 151 794 3753
FAX:   +44 151 794 4442

**Comment by alisonrclarke** [comment]
> Certainly, the title in bede-README-sbatch.rst is Watson Machine Learning Community Edition resnet50 benchmark so the heading could be WMLCE resnet50 benchmark. (Just spotted another typo – I had Environment rather than Edition in bede-README-sbatch.rst – will push out correction when possible). This probably would work as a sub-heading to the topic that Mark created: PyTorch and TensorFlow: IBM PowerAI and Watson Machine Learning Community Edition (wmlce) [Possibly Out of Date] Cliff

Thanks. I've adjusted the title now, and I've put these sections under a "python" heading for now (until we look at #5 and split the software section into more pages).

**Comment by MarionBWeinzierl** [comment]
@alisonrclarke @jhodrien @caddison2016 , is there a reason that this PR is not yet merged in?

**Review by jhodrien — APPROVED** [review]
As far as I understood my comments had been addressed, so it's fine with me.

**Comment by alisonrclarke** [comment]
> @alisonrclarke @jhodrien @caddison2016 , is there a reason that this PR is not yet merged in?

I think @caddison2016 was going to push a commit with a small correction?

> (Just spotted another typo – I had Environment rather than Edition in bede-README-sbatch.rst – will push out correction when possible).

**Pull request merged**
