### PR TITLE
Fix link for registration details

### PR DESCRIPTION
**Pull request by jonathanfrawley**
Links to info about registration were not pointing anywhere. Fix this with a link to our registrations page.

### CODE REVIEW

**Review by MarionBWeinzierl — COMMENTED** [review]
I think it should be "For information" instead of "To information"?

**Review by MarionBWeinzierl — COMMENTED** [review]
And does the link need to be set to be a link explicitly?

**Comment by alisonrclarke** [comment]
> And does the link need to be set to be a link explicitly

Sphinx does that automatically. (You can check the build artifact from CI to download a built copy of the docs.)

**Review by alisonrclarke — COMMENTED** [review]
Looks good to me once you've addressed Marion's comment about To/For.

**Comment by jonathanfrawley** [comment]
Thanks, I have fixed that now.

**Review by alisonrclarke — APPROVED** [review]

**Pull request merged**
