### PR TITLE
Use new theme for docs

### PR DESCRIPTION
**Pull request by alisonrclarke**
Partial fix for #5 though this is more of a restyling than a restructuring.

Uses bootstrap theme, customised to use N8 theme. (Hoping to get a clearer logo from Niki soon.)

You can see the generated docs at: https://arclarke-docs-test.readthedocs.io/en/latest/index.html

### CODE REVIEW

**Comment by alisonrclarke** [comment]
Have now added new logo.

**Comment by MarionBWeinzierl** [comment]
image
Why are these numbers highlighted?

**Comment by alisonrclarke** [comment]
> image
> Why are these numbers highlighted?

Must just be how they were copied over from the hackathon docs. Will remove code highlighting for the version numbers. Guess it might also be worth re-colouring the code highlighting within a note?

**Comment by MarionBWeinzierl** [comment]
> > image
> > Why are these numbers highlighted?
> 
> Must just be how they were copied over from the hackathon docs. Will remove code highlighting for the version numbers. Guess it might also be worth re-colouring the code highlighting within a note?

Yes, doesn't look too pretty

**Comment by MarionBWeinzierl** [comment]
I've tested building it and it works perfectly. Even without the warning that I get on the main branch. :+1:

**Review by MarionBWeinzierl — APPROVED** [review]

**Pull request merged**
