### PR TITLE
Grace-Hopper non-pilot documentation

### LINKED ISSUE #185: Grace-Hopper documentation
Initial Grace-hopper documentation has been added by #183.

As the software availability is different on the grace-hopper (aarch64) nodes than Power (ppc64le) nodes, the documentation needs expanding to cover this. 

This could be done by:

1. Use the existing software pages, clarifying which arch it is available for, with per arch instructions where required (i.e. pytorch via container not conda). 
2. Split the software section into 2 per arch sections (with redirects from the current URI to the ppc64uri, and cross-links from each common page). 

The tradeoff is duplication vs how users are likely to find the docs. 

I.e. are users going to look for software, or look for arch then software. 

Notable inclusions / changes needed (include content added in #183 to the usage pilot section):

+ CUDA 11.8+ for SM 90, else PTX required
+ Apptainer vs Singularity
+ Conda/pip pytorch not CUDA enabled, use source builds or Nvidia containers
+ GCC psABI warnings
+ No opence on aarch, same for other modules.

### PR DESCRIPTION
**Pull request by ptheywood**
Adds non-pilot grace-hopper specific documentation. 

Closes #185

+ [x] Usage page
    + [x] Add ghlogin partition detail
    + [x] Add CPU architecture/ Partitions subsection explaining which are which
    + [x] Reduce GH pilot subsection to be less content + links, stating that the pilot has ended. To be removed at a future date
+ [x] Add announcement stating 3 GH200 480GB nodes are now avialable
    + [x] link to a usage subsection?
+ [x] Remove wmlce documentation (via orphan)
+ [x] Add admonition to each ppc64le only page
+ [x] Add gh details to each software page
    + [x] Conda
    + [x] Python
      + [x] Check if python2 is still available. Change that bit to be architecture specific
      + [x] Make default python version information partition specific.
    + [x] pytorch
        + Include how to get a CUDA enabled build at the mo
    + [x] Rust - no changes needed
    + [x] Tensorflow
        + Include how to get a CUDA enabled build at the mo
    + [x] CUDA/NVCC
        + Modules, CUDA verisons & limitations, gencodes
    + [x] GCC
        + [x] mention psABI warnings and how to suppress.
        + [x] Double check / reprhase psabi docs
    + [x] NVHPC
    + [x] Blas/Lapack (OpenBLAS)
        + ~Maybe split this page into3. Current page and one per implementation so its clearer which are availabe on which platform.~ defferred to #192 
    + [x] Boost
    + [x] FFTW
    + [x] HDF5
    + [x] OpenMPI
        + ~Maybe split  MPI page so its clearer which is available where~ deferred to #191 
    + [x] NVTX
    + [x] CMake (no modules)
    + [x] Make
    + [x] `ncu`
      + [x] add version info 
    + [x] `nsys`
      + [x] add version info
    + [x] `nvidia-smi`
    + [x] Apptainer/Singularity documentation. 
        + Current plan is for ppc64le to continue with singularity to avoid unneccesary breaking changes
        + [x] Apptainer page - just aarch64, cross ref singularity CE. Mention fakeroot.
        + [x] Singularity - rename singularity CE. ppc64le only. Cross ref Apptainer 
+ [x] Add arch bash detection for .bashrc to faq and usage.
+ [x] Basic tabs theme customisation
+ [x] Finished tabs theme customisation (code tabs don't look great) 
+ Guides
   + ~Add a guide for running a pytorch workflow on gracehopper as an example?~ Deffered to #193
   + This might be deffered to a separate issue
+ [x] sidebar and non-sidebar common admonitions and use the.

### CODE REVIEW

**Comment by bodgerer** [comment]
Hi Peter! Thanks so much for this, it's looking really good. Love the tabs and how they remember which tab you were looking at in the previous box :)
  
One thing though: someone has been trying out MPI on the Grace Hoppers, and I've recently needed to generate a bede-mpirun to get things running. It has the same semantics as the ppc64le version (although as there's no hardware SMT, the 1ppt option is fairly pointless).
  
There are two references on the usage page to using mpirun rather than bede-mpirun on aarch64... can these be removed, please?

Other than that, looks good to go to me.

Best,

Mark

**Comment by bodgerer** [comment]
Oh, and the gh mpi example would need updating, too. Sorry!

**Comment by ptheywood** [comment]
0fea0493d8fe9003fd81c18f510606df7df058af re-combines the aarch and ppc64le mpi usage section, with the tab jsut differntiating the job script by partition now. 
There is also a `.. note::` pointing out `1ppt` is the same as `1ppc` on gh.

I've updated the suggestion to use mpirun to now be bede-mpirun in the gh pilot section.

**Comment by ptheywood** [comment]
I'll get this merged now, and we can tweak it more in the future if any other adjustments are needed / mistakes spotted.

**Pull request merged**
