### PR TITLE
Revised WMLCE + Open-CE documentation.

### LINKED ISSUE #63: confusion with wmcle
I had a user who was confused by "Powerai and wmlce" saying "Possibly Out of Date" and going to the IBM site.  I guess it should say that's superseded by opence, which dropped the large model support.
There could be a pointer to the LM patches, and the discussions about (not) merging them, in case someone is motivated to update them.

### LINKED ISSUE #72: Resnet50 benchmark scripts no longer usable
The Resenet50 benchmark job scripts are no longer usable on bede, as `/opt/software/apps/anaconda3` does not exist.

Additionally, moving to RHEL8 where WMLCE is not supported (instead replaced by OpenCE) it is unclear if `ddlrun` and therefore `bede-ddlrun` will be usable.

It may be worth re-benchmarking RESNET50 prior to the RHEL8 switch so we know the performance impact of WMLCE vs OpenCE?

I.e. run RESNET50 at a number of scales (1, 2, 4, 8, 12?, 16? GPUs, current docs say no need to go larger) with:

+ RHEL7, WMLCE
+ RHEL 7, OpenCE, ideally matching WMLCE TF version
+ RHEL 7, OpenCE lastest
+ RHEL 8, OpenCE older
+ RHEL 8, OpenCE latest?

The current RHEL8 testing partition only conatisn 2 nodes, so only up to 8 GPUs will currently  be usable for RHEL8.

This is closely related to #63

### PR DESCRIPTION
**Pull request by ptheywood**
Improves the state of WMLCE documentation, adds Open-CE documentation and updates Tensorflow/PyTorch to reflect this change.

+ [x] Updates WMLCE page
  + [x] Document current project status (Deprecated / unsupported)
  + [x] Clearly state that users should probably switch to Open-CE or upstream distributions
  + [x] Verify if it is still usable on RHEL 8 or not, update accordingly
    + Errors occured when attempting to `bede-ddlrun` on RHEL 8. 
  + [x] Update usage instructions to no longer be `[Possibly Out of Date]`.
  + [x] Update `WMLCE resnet50 benchmark` section
    + This is only available via WMLCE with a licence which may prevent distribution outside of WMLCE so not re-running to generate results.
    + DDLrun errors on RHEL 8 as expected, so not useful to compare wmlce on 7 vs 8.
+ [x] Adds a page documenting Open-CE, the successor to WMLCE.
  + [x] Basic Description
  + [x] Usage with example
    + [x] Verify instructions
  + [x] Why should someone use Open-CE rather than upstream TF/pytorch?
  + [x] Clear description of missing WMLCE features (LMS, DDLRUN?, Others?)
  + ~Benchmarking, use the resnet benchmark from above on <= 4 nodes?~
    + Not benchmarking as WMLCE tensorflow-benchmarks is not openly licenced by ibm, and ddlrun doesn't work. 
  + [x] Cross reference TF, Pytorch, WMLCE.
+ [x] Add cross references to Open-CE from Tensorflow, Conda and Pytorch pages

Closes #63 
Closes #72

### CODE REVIEW

**Comment by ptheywood** [comment]
This may also have to include updates to general miniconda installation instructions. 

The current instructions for installing into `/nobackup/projects/<project>` will actually install int /users/. 

```bash
sh Miniconda3-latest-Linux-ppc64le.sh -b -p $(pwd)/miniconda
```
The above will install silently into a directory `miniconda` within the current directory and not update the users `.bashrc` which may or may not be desirable.

**Comment by ptheywood** [comment]
Aditionally, the current wmlce instructions add the wmlce channel to the users global conda channel configuration, not per environment. 

This breaks subsequent use of open-ce. There is likely need to add instructions on how to deal with this (i.e. if an `unsatisfiableError` is raised). 

It would also be better to adjust he wmlce instructions to only set the channel within the environment. The same applies to Open-CE (via the conda `--env` flag on conda config --set`?)

**Comment by ptheywood** [comment]
The WMLCE `tensorflow-benchmarks/resnet50` benchmark script is not included in Open-CE. It is Apahce 2 licenced by Nvidia, but with IBM modifications with the follwoing restrictive / unclear licence, so I am not going to make this available for use outside of wmlce, so can't use this for a comparitive benchmark.

> Licensed Materials - Property of IBM
(C) Copyright IBM Corp. 2020. All Rights Reserved.
US Government Users Restricted Rights - Use, duplication or
disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

The existing WMLCE benchmark on RHEL 7 with ddlrun and 4 gpus in a single node behaves as described, although it suspiciously took 15 seconds less than the 5 hours I requested( compared to 4 hours as previously suggested). 

Attempting to run this via `bede-ddlrun` on the RHEL 8 image errored with the following:

```
No active IB device ports detected
[gpu013.bede.dur.ac.uk:98383] Error: common_pami.c:1087 - ompi_common_pami_init() 0: Unable to create 1 PAMI communication context(s) rc=1
No active IB device ports detected
[gpu013.bede.dur.ac.uk:98384] Error: common_pami.c:1087 - ompi_common_pami_init() 1: Unable to create 1 PAMI communication context(s) rc=1
No active IB device ports detected
[gpu013.bede.dur.ac.uk:98386] Error: common_pami.c:1087 - ompi_common_pami_init() 3: Unable to create 1 PAMI communication context(s) rc=1
No active IB device ports detected
[gpu013.bede.dur.ac.uk:98385] Error: common_pami.c:1087 - ompi_common_pami_init() 2: Unable to create 1 PAMI communication context(s) rc=1
--------------------------------------------------------------------------
No components were able to be opened in the pml framework.

This typically means that either no components of this type were
installed, or none of the installed components can be loaded.
Sometimes this means that shared libraries required by these
components are unable to be found/loaded.

  Host:      gpu013
  Framework: pml
--------------------------------------------------------------------------
[gpu013.bede.dur.ac.uk:98383] PML pami cannot be selected
[gpu013.bede.dur.ac.uk:98357] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2079
[gpu013.bede.dur.ac.uk:98357] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2079
[gpu013.bede.dur.ac.uk:98357] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2079
[gpu013.bede.dur.ac.uk:98386] PML pami cannot be selected
[gpu013.bede.dur.ac.uk:98384] PML pami cannot be selected
[gpu013.bede.dur.ac.uk:98385] PML pami cannot be selected
[gpu013.bede.dur.ac.uk:98357] 3 more processes have sent help message help-mca-base.txt / find-available:none found
[gpu013.bede.dur.ac.uk:98357] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

---------------
Job output ends
=========================================================
SLURM job: finished date = Tue 1 Mar 18:22:12 GMT 2022
Total run time : 0 Hours 1 Minutes 29 Seconds
=========================================================
```

This appears to confirm that ddlrun/bede-ddlrun does not work on the RHEL 8 nodes, though I'll double check this via slack later. 

Attempting to run the benchmark on RHEL 8 without ddlrun, using a single GPU in a single node resulted in the job being killed for OOM.

```
---------------
Job output ends
=========================================================
SLURM job: finished date = Tue 1 Mar 22:13:38 GMT 2022
Total run time : 0 Hours 52 Minutes 24 Seconds
=========================================================
slurmstepd: error: Detected 1 oom-kill event(s) in step 356980.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

I.e. it requires more than 1/4 of the node's memory, but otherwise WMLCE tensorflow does appear to work on RHEL 8, though given its very EOL most users should migrate to Open-CE or upstream tensorflow (and lose LMS)

Running the single GPU version on RHEL 7 also died due to OOM, but several hours further into the run.

To benchmark this, correctly, requesting a full node but only making one device available by `CUDA_VISIBLE_DEVICES`, or an inner srun might be required, but if this is not going to be directly comparable to a WMLCE or RHEL 8 benchmark of the same model it's probably not worthwhile reproducing / benchmarking. 

Finding a more recent / more open benchmark to run might be a better plan. 

```
=========================================================
SLURM job: finished date = Wed 2 Mar 00:49:40 GMT 2022
Total run time : 3 Hours 15 Minutes 36 Seconds
=========================================================
slurmstepd: error: Detected 1 oom-kill event(s) in step 356990.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```

**Comment by loveshack** [comment]
I don't now remember the context, but I guess if it's documented to use
open-ce rather than wmlce, that's OK.  For what it's worth, there's
something about it in the Summit docs (specifically about RHEL8, I
think).

**Review by jsteyn — APPROVED** [review]

**Pull request merged**
