### PR TITLE
Add PyTorch quickstart guide

### LINKED ISSUE #21: Add tutorial about how to use newer PyTorch on Bede
Info here: https://gist.github.com/qazwsxal/e5dff94c2fe36f0850b5e10a58293a7b

This will not suit everyone as it lacks LMS but it is probably useful for many people.

### PR DESCRIPTION
**Pull request by jonathanfrawley**
Old instructions do not work for me any more. These instructions were provided by Adam Leach in Durham.

Closes #21

### CODE REVIEW

**Review by MarionBWeinzierl — APPROVED** [review]

**Review by alisonrclarke — APPROVED** [review]
Looks good. Just wondered if it's worth linking to the gist in case anyone wants a more detailed explanation?

**Comment by jonathanfrawley** [comment]
I actually removed the link as I am not sure he wanted to share the Gist widely (I believe there were project specific directories / info in it).

**Comment by loveshack** [comment]
Why should users have to trash an existing installation, and even any
directory they have in the project lustre directory?  That doesn't seem
right.

I'd have thought installations like that should actually be on NFS.
However, given it's 6GB, shouldn't it be installed centrally?  (It comes
in a lot smaller as a default spack package, using the system cuda etc.)

**Comment by jonathanfrawley** [comment]
It's just a quick start guide which is hopefully useful for people starting a new project. I would have said to put it in their home directory but I ran out of disk space doing that.
The problem with installing centrally is that a lot of machine learning researchers use slightly different versions of libraries like PyTorch, Tensorflow. Also, they are usually used to using conda as a tool.

**Comment by loveshack** [comment]
Jonathan Frawley <notifications@github.com> writes:

> It's just a quick start guide which is hopefully useful for people
> starting a new project.

Sure, but I'm making an educated guess at what a user or two will end up
doing and complain about.  If it is new, they don't need to delete
stuff, and may not have the project sub-directory.

> I would have said to put it in their home
> directory but I ran out of disk space doing that.

Yes, that's why I looked at potentially (somewhat) better engineering;
things have got really out of hand.

> The problem with installing centrally is that a lot of machine
> learning researchers use slightly different versions of libraries like
> PyTorch, Tensorflow. Also, they are usually used to using conda as a
> tool.

I don't usually get a good answer when I ask why not use improved
versions, modulo occasional regressions.  Installing the latest version
centrally doesn't hurt, anyway, does it?  They can ignore it or stack
their own stuff on top, can't they?  Using conda is a good reason not to
trash ~/.conda, by copying instructions more-or-less blindly.  If they
copy less blindly, and set DIR=$HOME, cutting and pasting rm -r is
particularly bad news; I'm not sure how much to bet on that happening,
but I've been around!

**Comment by jonathanfrawley** [comment]
Sorry, just picked this up now, the `rm -r` was a bad idea, you are right. I have commented those out now in #28 and said that if you want to reset your env to uncomment.

**Pull request merged**
