### PR TITLE
Feature/add faq section

### LINKED ISSUE #9: Add FAQ section
Add section for frequently asked questions, which will be updated continuously (hopefully!).

### PR DESCRIPTION
**Pull request by kilicomu**
Adds the basis for an FAQ section, and an example question/answer.

@MarionBWeinzierl Do you have a list of questions ready to go in this section?

Closes #9.

### CODE REVIEW

**Comment by MarionBWeinzierl** [comment]
I have no list yet, but #38 ,  #39 , #16 and #12 would be good candidates. You could also have a look at https://mit-satori.github.io/satori-doc-examples-contributing.html and see what is useful.

**Review by MarionBWeinzierl — COMMENTED** [review]
Could you please also check how this works in the menu (as it might overflow in the menu)? @alisonrclarke is our chief designer and might be able to advise.

**Comment by kilicomu** [comment]
@MarionBWeinzierl Which menu are you referring to? If it's the navbar menu - it doesn't overflow it at viewport sizes before the smaller viewport styling kicks in. If it's the hamburger menu at smaller viewport sizes, it also doesn't overflow that menu. 

Another menu maybe?

**Comment by MarionBWeinzierl** [comment]
I was talking about the menu on the top of the window -- @alisonrclarke tested those in several browsers to make sure it does not overflow (especially if you resize the window). Alison, could you advise which one was the critical case when you did this?

**Comment by kilicomu** [comment]
Ah I see - in both Safari and Chromium the search bar is displaced to a 'new row'.

**Comment by MarionBWeinzierl** [comment]
Yes, exactly, I think that was what Alison mentioned.

**Comment by alisonrclarke** [comment]
A second menu is not straightforward in sphinx. I wonder if we need to rethink the existing menu? Currently there's not actually much under 'Hardware', and there seems to be some overlap between 'software' and 'usage' (i.e. some of the Software sections are about how to use Bede.)

**Comment by kilicomu** [comment]
Just pushed an opinionated fix that removes the 'Documentation' title from the navbar and resolves the overflow issue (for now...) for Chromium and Safari. This will hold up until we add a couple more items to the navbar, which will _probably never happen_...

**Comment by kilicomu** [comment]
I've added a few questions as a starting point.

**Comment by kilicomu** [comment]
Ah, I was going to rebase my fork but you already merged main into the branch! My force has probably overwritten that...

**Review by MarionBWeinzierl — APPROVED** [review]

**Pull request merged**
